AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FranquiciasTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'Franquicias'
      AttributeDefinitions:
        - AttributeName: 'franquiciaId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'franquiciaId'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST

  SucursalesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'Sucursales'
      AttributeDefinitions:
        - AttributeName: 'sucursalId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'sucursalId'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST

  ProductosTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'Productos'
      AttributeDefinitions:
        - AttributeName: 'productoId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'productoId'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST

  FranquiciaSucursalTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'FranquiciaSucursal'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST

  SucursalProductoTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'SucursalProducto'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
